# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#featured_publications"
  weight = 40

# [[main]]
#   name = "Languages"
#   url = "#languages"
#   weight = 50

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 60

[[main]]
  name = "Grants"
  url = "#grants"
  weight = 70

[[main]]
  name = "Blog"
  url = "#blog"
  weight = 80

# [[main]]
#   name = "Mentors"
#   url = "#mentors"
#   weight = 90

[[main]]
  name = "Teams"
  url = "#experience_research"
  weight = 100

# [[main]]
#   name = "Volunteer"
#   url = "#experience_volunteer"
#   weight = 110

[[main]]
  name = "Topics"
  url = "#tags"
  weight = 120

# [[main]]
#   name = "Contact"
#   url = "#contact"
#   weight = 130

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
